INSERT INTO Listings_Info(listing_id,name) VALUES ('2539','Clean & quiet apt home by the park');
INSERT INTO Listings_Info(listing_id,name) VALUES ('2595','Skylit Midtown Castle');
INSERT INTO Listings_Info(listing_id,name) VALUES ('3647','THE VILLAGE OF HARLEM....NEW YORK !');
INSERT INTO Listings_Info(listing_id,name) VALUES ('3831','Cozy Entire Floor of Brownstone');
INSERT INTO Listings_Info(listing_id,name) VALUES ('5022','Entire Apt: Spacious Studio/Loft by central park');
INSERT INTO Listings_Info(listing_id,name) VALUES ('5099','Large Cozy 1 BR Apartment In Midtown East');
INSERT INTO Listings_Info(listing_id,name) VALUES ('5121','BlissArtsSpace!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('5178','Large Furnished Room Near B''way');
INSERT INTO Listings_Info(listing_id,name) VALUES ('5203','Cozy Clean Guest Room - Family Apt');
INSERT INTO Listings_Info(listing_id,name) VALUES ('5238','Cute & Cozy Lower East Side 1 bdrm');
INSERT INTO Listings_Info(listing_id,name) VALUES ('5295','Beautiful 1br on Upper West Side');
INSERT INTO Listings_Info(listing_id,name) VALUES ('5441','Central Manhattan/near Broadway');
INSERT INTO Listings_Info(listing_id,name) VALUES ('5803','Lovely Room 1, Garden, Best Area, Legal rental');
INSERT INTO Listings_Info(listing_id,name) VALUES ('6021','Wonderful Guest Bedroom in Manhattan for SINGLES');
INSERT INTO Listings_Info(listing_id,name) VALUES ('6090','West Village Nest - Superhost');
INSERT INTO Listings_Info(listing_id,name) VALUES ('6848','Only 2 stops to Manhattan studio');
INSERT INTO Listings_Info(listing_id,name) VALUES ('7097','Perfect for Your Parents + Garden');
INSERT INTO Listings_Info(listing_id,name) VALUES ('7322','Chelsea Perfect');
INSERT INTO Listings_Info(listing_id,name) VALUES ('7726','Hip Historic Brownstone Apartment with Backyard');
INSERT INTO Listings_Info(listing_id,name) VALUES ('7750','Huge 2 BR Upper East  Cental Park');
INSERT INTO Listings_Info(listing_id,name) VALUES ('7801','Sweet and Spacious Brooklyn Loft');
INSERT INTO Listings_Info(listing_id,name) VALUES ('8024','CBG CtyBGd HelpsHaiti rm#1:1-4');
INSERT INTO Listings_Info(listing_id,name) VALUES ('8025','CBG Helps Haiti Room#2.5');
INSERT INTO Listings_Info(listing_id,name) VALUES ('8110','CBG Helps Haiti Rm #2');
INSERT INTO Listings_Info(listing_id,name) VALUES ('8490','MAISON DES SIRENES1,bohemian apartment');
INSERT INTO Listings_Info(listing_id,name) VALUES ('8505','Sunny Bedroom Across Prospect Park');
INSERT INTO Listings_Info(listing_id,name) VALUES ('8700','Magnifique Suite au N de Manhattan - vue Cloitres');
INSERT INTO Listings_Info(listing_id,name) VALUES ('9357','Midtown Pied-a-terre');
INSERT INTO Listings_Info(listing_id,name) VALUES ('9518','SPACIOUS, LOVELY FURNISHED MANHATTAN BEDROOM');
INSERT INTO Listings_Info(listing_id,name) VALUES ('9657','Modern 1 BR / NYC / EAST VILLAGE');
INSERT INTO Listings_Info(listing_id,name) VALUES ('9668','front room/double bed');
INSERT INTO Listings_Info(listing_id,name) VALUES ('9704','Spacious 1 bedroom in luxe building');
INSERT INTO Listings_Info(listing_id,name) VALUES ('9782','Loft in Williamsburg Area w/ Roof');
INSERT INTO Listings_Info(listing_id,name) VALUES ('9783','back room/bunk beds');
INSERT INTO Listings_Info(listing_id,name) VALUES ('10452','Large B&B Style rooms');
INSERT INTO Listings_Info(listing_id,name) VALUES ('10962','Lovely room 2 & garden; Best area, Legal rental');
INSERT INTO Listings_Info(listing_id,name) VALUES ('11452','Clean and Quiet in Brooklyn');
INSERT INTO Listings_Info(listing_id,name) VALUES ('11708','Cute apt in artist''s home');
INSERT INTO Listings_Info(listing_id,name) VALUES ('11943','Country space in the city');
INSERT INTO Listings_Info(listing_id,name) VALUES ('12048','LowerEastSide apt share shortterm 1');
INSERT INTO Listings_Info(listing_id,name) VALUES ('12192','ENJOY Downtown NYC!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('12299','Beautiful Sunny Park Slope Brooklyn');
INSERT INTO Listings_Info(listing_id,name) VALUES ('12303','1bdr w private bath. in lofty apt');
INSERT INTO Listings_Info(listing_id,name) VALUES ('12318','West Side Retreat');
INSERT INTO Listings_Info(listing_id,name) VALUES ('12343','BEST BET IN HARLEM');
INSERT INTO Listings_Info(listing_id,name) VALUES ('12627','Entire apartment in central Brooklyn neighborhood.');
INSERT INTO Listings_Info(listing_id,name) VALUES ('12937','1 Stop fr. Manhattan! Private Suite,Landmark Block');
INSERT INTO Listings_Info(listing_id,name) VALUES ('12940','Charming Brownstone 3 - Near PRATT');
INSERT INTO Listings_Info(listing_id,name) VALUES ('13050','bright and stylish duplex');
INSERT INTO Listings_Info(listing_id,name) VALUES ('13394','Fort Greene brownstone');
INSERT INTO Listings_Info(listing_id,name) VALUES ('13808','Blue Room for 2 in Brownstone for $1350 monthly');
INSERT INTO Listings_Info(listing_id,name) VALUES ('14287','Cozy 1BD on Central Park West in New York City');
INSERT INTO Listings_Info(listing_id,name) VALUES ('14290','* ORIGINAL BROOKLYN LOFT *');
INSERT INTO Listings_Info(listing_id,name) VALUES ('14314','Greenpoint Place...Has It All!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('14322','Beautiful Apartment in Manhattan!!!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('14377','Williamsburg 1 bedroom Apartment');
INSERT INTO Listings_Info(listing_id,name) VALUES ('14991','Great Location, Manhattan Bedroom!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('15220','Best Location in NYC! TIMES SQUARE!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('15338','Room in Greenpoint Loft w/ Roof');
INSERT INTO Listings_Info(listing_id,name) VALUES ('15341','**Bright Nolita Apt w Doorman/Elevators/Gym**');
INSERT INTO Listings_Info(listing_id,name) VALUES ('15385','Very, very cozy place');
INSERT INTO Listings_Info(listing_id,name) VALUES ('15396','Sunny & Spacious Chelsea Apartment');
INSERT INTO Listings_Info(listing_id,name) VALUES ('15711','2 bedroom - Upper East Side-great for kids');
INSERT INTO Listings_Info(listing_id,name) VALUES ('16326','Comfortable 4-bedroom apt in family house.');
INSERT INTO Listings_Info(listing_id,name) VALUES ('16338','Double Room w Private Deck Clinton Hill Best Area');
INSERT INTO Listings_Info(listing_id,name) VALUES ('16421','Your Heaven in Hells Kitchen');
INSERT INTO Listings_Info(listing_id,name) VALUES ('16458','Light-filled 2B duplex in the heart of Park Slope!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('16580','Sunny, Modern room in East Village!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('16595','*HAVEN LOFT - Entire Floor - Six Windows - Bricks*');
INSERT INTO Listings_Info(listing_id,name) VALUES ('16821','Large Room in Amazing East Village Apt');
INSERT INTO Listings_Info(listing_id,name) VALUES ('16974','SpaHa Loft: Enormous and Bright');
INSERT INTO Listings_Info(listing_id,name) VALUES ('17037','Lovely EV Artist''s Home');
INSERT INTO Listings_Info(listing_id,name) VALUES ('17092','Cool Room in Hell''s Kitchen');
INSERT INTO Listings_Info(listing_id,name) VALUES ('17693','HARLEM, NEW YORK WELCOMES YOU!!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('17747','BLUE TRIM GUEST HOUSE');
INSERT INTO Listings_Info(listing_id,name) VALUES ('18127','Charming East Village One Bedroom Flat');
INSERT INTO Listings_Info(listing_id,name) VALUES ('18152','Manhattan Room');
INSERT INTO Listings_Info(listing_id,name) VALUES ('18198','Little King of Queens');
INSERT INTO Listings_Info(listing_id,name) VALUES ('18590','Fort Greene Retreat on the Park');
INSERT INTO Listings_Info(listing_id,name) VALUES ('18728','Beautiful Meatpacking District Loft');
INSERT INTO Listings_Info(listing_id,name) VALUES ('18764','Cozy 2 BR in Williamsburg');
INSERT INTO Listings_Info(listing_id,name) VALUES ('19159','Spacious luminous apt Upper West NYC');
INSERT INTO Listings_Info(listing_id,name) VALUES ('19169','Entire 2 Bedroom - Large & Sunny');
INSERT INTO Listings_Info(listing_id,name) VALUES ('19282','Sunny, Spacious Top Floor Haven');
INSERT INTO Listings_Info(listing_id,name) VALUES ('19319','Private room Great Deal at Lower East Side');
INSERT INTO Listings_Info(listing_id,name) VALUES ('19601','perfect for a family or small group');
INSERT INTO Listings_Info(listing_id,name) VALUES ('19812','2 bedroom Williamsburg Apt - Bedford L stop');
INSERT INTO Listings_Info(listing_id,name) VALUES ('20299','Oh glorious spring!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('20300','Great Location for NYC');
INSERT INTO Listings_Info(listing_id,name) VALUES ('20611','Cozy Bedroom in Williamsburg 3 BR');
INSERT INTO Listings_Info(listing_id,name) VALUES ('20724','Sunny room+Pvte office in huge loft');
INSERT INTO Listings_Info(listing_id,name) VALUES ('20734','Spacious Prospect Heights Apartment');
INSERT INTO Listings_Info(listing_id,name) VALUES ('20755','Large Parlor Room, Landmark Home 1 block to PRATT');
INSERT INTO Listings_Info(listing_id,name) VALUES ('20853','2-bed brownstone duplex + garden');
INSERT INTO Listings_Info(listing_id,name) VALUES ('20913','Charming 1 bed GR8 WBurg LOCATION!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('21293','Sunny Apartment in Artist Home');
INSERT INTO Listings_Info(listing_id,name) VALUES ('21456','Light-filled classic Central Park');
INSERT INTO Listings_Info(listing_id,name) VALUES ('21644','Upper Manhattan, New York');
INSERT INTO Listings_Info(listing_id,name) VALUES ('21794','COZY QUIET room 4 DOOGLERS!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('22911','The Stuydio Modern and Light Filled');
INSERT INTO Listings_Info(listing_id,name) VALUES ('22918','loft bed - near transportation-15min to times sq');
INSERT INTO Listings_Info(listing_id,name) VALUES ('23135','House On Henry (3rd FLR Suite)');
INSERT INTO Listings_Info(listing_id,name) VALUES ('23501','Monkey Retreat Manhattan');
INSERT INTO Listings_Info(listing_id,name) VALUES ('23686','2000 SF 3br 2bath West Village private  townhouse');
INSERT INTO Listings_Info(listing_id,name) VALUES ('24143','Williamsburg—Steps To Subway, Private Bath&Balcony');
INSERT INTO Listings_Info(listing_id,name) VALUES ('24285','Beautiful Duplex Apartment');
INSERT INTO Listings_Info(listing_id,name) VALUES ('25235','Large 2 Bedroom Great for Groups!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('25406','Modern Brooklyn Apt., August sublet');
INSERT INTO Listings_Info(listing_id,name) VALUES ('25696','1,800 sq foot in luxury building');
INSERT INTO Listings_Info(listing_id,name) VALUES ('26012','Sunny 2-story Brooklyn townhouse w deck and garden');
INSERT INTO Listings_Info(listing_id,name) VALUES ('26362','Times Square, Safe, Clean and Cozy!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('26520','Cozy Room #3, Landmark Home 1 Block to PRATT');
INSERT INTO Listings_Info(listing_id,name) VALUES ('26559','Beautiful Apartment East Village');
INSERT INTO Listings_Info(listing_id,name) VALUES ('26785','Park Slope Green Guest House');
INSERT INTO Listings_Info(listing_id,name) VALUES ('26933','2 BR / 2 Bath Duplex Apt with patio! East Village');
INSERT INTO Listings_Info(listing_id,name) VALUES ('26954','NYC fabulous views Manhattan''s eye');
INSERT INTO Listings_Info(listing_id,name) VALUES ('26969','2 story family home in Williamsburg');
INSERT INTO Listings_Info(listing_id,name) VALUES ('27006','Comfortable UWS 2-BD Family-Friendly Brownstone');
INSERT INTO Listings_Info(listing_id,name) VALUES ('27385','Great Large 1 BR apt  in East Village!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('27531','Eveland Private Bed & Living Room w/ Own Entrance');
INSERT INTO Listings_Info(listing_id,name) VALUES ('27644','Sugar Hill Rest Stop');
INSERT INTO Listings_Info(listing_id,name) VALUES ('27659','3 Story Town House in Park Slope');
INSERT INTO Listings_Info(listing_id,name) VALUES ('27759','apartment next to Central park');
INSERT INTO Listings_Info(listing_id,name) VALUES ('27883','East Village Sanctuary');
INSERT INTO Listings_Info(listing_id,name) VALUES ('28321','Large 1  BR in a 3 BR Brooklyn apt. next to Q Trn.');
INSERT INTO Listings_Info(listing_id,name) VALUES ('28396','Modern Apt with Spectacular Views');
INSERT INTO Listings_Info(listing_id,name) VALUES ('28907','Garden studio in the Upper East Sid');
INSERT INTO Listings_Info(listing_id,name) VALUES ('29012','Secluded Master Bedroom in Beautiful Huge Apt');
INSERT INTO Listings_Info(listing_id,name) VALUES ('29013','B & B Room 1');
INSERT INTO Listings_Info(listing_id,name) VALUES ('29455','ACCOMMODATIONS GALORE #1');
INSERT INTO Listings_Info(listing_id,name) VALUES ('29628','Sunny Room in New Condo');
INSERT INTO Listings_Info(listing_id,name) VALUES ('29683','Stylish & Sleek Apartment Near SoHo!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('30031','NYC artists’ loft with roof deck');
INSERT INTO Listings_Info(listing_id,name) VALUES ('30927','Unique & Charming small 1br Apt. LES');
INSERT INTO Listings_Info(listing_id,name) VALUES ('31130','Most Central Location!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('31555','Luminous Beautiful West Village Studio');
INSERT INTO Listings_Info(listing_id,name) VALUES ('31902','Sanctuary in East Flatbush');
INSERT INTO Listings_Info(listing_id,name) VALUES ('31994','Room with En Suite Bathroom & Deck');
INSERT INTO Listings_Info(listing_id,name) VALUES ('32023','FLAT MACDONOUGH');
INSERT INTO Listings_Info(listing_id,name) VALUES ('32037','Huge Private  Floor at The Waverly');
INSERT INTO Listings_Info(listing_id,name) VALUES ('32100','Modern Greenpoint, Brooklyn Apt');
INSERT INTO Listings_Info(listing_id,name) VALUES ('32289','Sun-drenched, artsy modernist 1 BDRM duplex');
INSERT INTO Listings_Info(listing_id,name) VALUES ('32331','Sunny, Cobble Hill Apartment');
INSERT INTO Listings_Info(listing_id,name) VALUES ('32363','Fully Furnished Basement Apartment');
INSERT INTO Listings_Info(listing_id,name) VALUES ('32965','FLAT MACDONOUGH GARDEN');
INSERT INTO Listings_Info(listing_id,name) VALUES ('32969','Light filled Williamsburg Apartment');
INSERT INTO Listings_Info(listing_id,name) VALUES ('33009','Retreat in Williamsburg');
INSERT INTO Listings_Info(listing_id,name) VALUES ('33014','NYC Zen');
INSERT INTO Listings_Info(listing_id,name) VALUES ('33223','Cozy BR in Wiliamsburg 3 Bedroom');
INSERT INTO Listings_Info(listing_id,name) VALUES ('34760','Sunny Room in Old Historical Brooklyn Townhouse');
INSERT INTO Listings_Info(listing_id,name) VALUES ('35526','Sun Filled Classic West Village Apt');
INSERT INTO Listings_Info(listing_id,name) VALUES ('36121','Lg Rm in Historic Prospect Heights');
INSERT INTO Listings_Info(listing_id,name) VALUES ('36133','Classic Artist Loft Williamsburg');
INSERT INTO Listings_Info(listing_id,name) VALUES ('36442','Great location. Spacious on PROSPECT PARK');
INSERT INTO Listings_Info(listing_id,name) VALUES ('36647','Private Bdrm/Bathrm. New! Elevator!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('36703','Sunny, clean 1 bdrm in W. Village');
INSERT INTO Listings_Info(listing_id,name) VALUES ('36934','Great location in Williamsburg');
INSERT INTO Listings_Info(listing_id,name) VALUES ('38638','Light and Airy Upper East Side 1 BDR apartment');
INSERT INTO Listings_Info(listing_id,name) VALUES ('38663','Luxury Brownstone in Boerum Hill');
INSERT INTO Listings_Info(listing_id,name) VALUES ('39267','CENTRAL PARK LOFT all for YOU');
INSERT INTO Listings_Info(listing_id,name) VALUES ('39282','Indie-Chic Share In Williamsburg');
INSERT INTO Listings_Info(listing_id,name) VALUES ('39593','A room w/ a Manhattan view, longer stay');
INSERT INTO Listings_Info(listing_id,name) VALUES ('39704','Private, Large & Sunny 1BR w/W&D');
INSERT INTO Listings_Info(listing_id,name) VALUES ('40039','Luxurious Condo in DUBMO with View');
INSERT INTO Listings_Info(listing_id,name) VALUES ('40453','Charming & Cozy midtown loft any WEEK ENDS  !!!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('41348','* Spacious GARDEN Park Slope Duplex* 6 people max');
INSERT INTO Listings_Info(listing_id,name) VALUES ('41513','Convenient cozy cheap apt Manhattan');
INSERT INTO Listings_Info(listing_id,name) VALUES ('42580','Parlor Room In Victorian Townhouse');
INSERT INTO Listings_Info(listing_id,name) VALUES ('42729','House On Henry (2nd FLR Suite)');
INSERT INTO Listings_Info(listing_id,name) VALUES ('42882','New York room with a view');
INSERT INTO Listings_Info(listing_id,name) VALUES ('43957','Sunny cozy room in Brklyn townhouse');
INSERT INTO Listings_Info(listing_id,name) VALUES ('44096','Room with a View');
INSERT INTO Listings_Info(listing_id,name) VALUES ('44161','Light+Open+Airy+Rustic+Modern Loft');
INSERT INTO Listings_Info(listing_id,name) VALUES ('44212','West Inn 2 - East Village');
INSERT INTO Listings_Info(listing_id,name) VALUES ('44221','Financial District Luxury Loft');
INSERT INTO Listings_Info(listing_id,name) VALUES ('44229','BROOKLYN VICTORIAN STYLE SUITE.....');
INSERT INTO Listings_Info(listing_id,name) VALUES ('44288','Your own Lovely West Village Studio');
INSERT INTO Listings_Info(listing_id,name) VALUES ('44506','ACCOMMODATIONS GALORE#3. 1-5 GUESTS');
INSERT INTO Listings_Info(listing_id,name) VALUES ('45393','Greenwich Village Stylish Apartment');
INSERT INTO Listings_Info(listing_id,name) VALUES ('45542','Clean and Cozy Harlem Apartment');
INSERT INTO Listings_Info(listing_id,name) VALUES ('45556','Fort Greene, Brooklyn: Center Bedroom');
INSERT INTO Listings_Info(listing_id,name) VALUES ('45910','Beautiful Queens Brownstone! - 5BR');
INSERT INTO Listings_Info(listing_id,name) VALUES ('45936','Couldn''t Be Closer To Columbia Uni');
INSERT INTO Listings_Info(listing_id,name) VALUES ('45940','Bright Spacious Luxury Condo');
INSERT INTO Listings_Info(listing_id,name) VALUES ('46544','Park Slope haven 15 mins from Soho');
INSERT INTO Listings_Info(listing_id,name) VALUES ('46723','SAFE  AND BEAUTIFUL ACCOMODATION');
INSERT INTO Listings_Info(listing_id,name) VALUES ('46911','Large Room in private Brownstone in Park Slope');
INSERT INTO Listings_Info(listing_id,name) VALUES ('47199','NEW YORK CITY, 1 BDRM.(NEAR CENTRAL PARK & METRO)');
INSERT INTO Listings_Info(listing_id,name) VALUES ('47362','LARGE, COMFY 1BDR W/CHARACTER!!!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('47370','Chelsea Studio sublet 1 - 2 months');
INSERT INTO Listings_Info(listing_id,name) VALUES ('47926','LUX APT IN TIMES SQUARE NEW BUILDING');
INSERT INTO Listings_Info(listing_id,name) VALUES ('48719','Designer 1 BR Duplex w/ Terrace- Spectacular Views');
INSERT INTO Listings_Info(listing_id,name) VALUES ('50447','Lovely Apt & Garden;  Legal;  Best Area; Amenities');
INSERT INTO Listings_Info(listing_id,name) VALUES ('51438','1 Bedroom in 2 Bdrm Apt- Upper East');
INSERT INTO Listings_Info(listing_id,name) VALUES ('51485','Lower East Side $57~/night');
INSERT INTO Listings_Info(listing_id,name) VALUES ('51572','Prime Location in Manhattan');
INSERT INTO Listings_Info(listing_id,name) VALUES ('51850','( F) Excellent/Pvt Rm');
INSERT INTO Listings_Info(listing_id,name) VALUES ('53137','Quiet, sunny Midtown Manhattan apt.');
INSERT INTO Listings_Info(listing_id,name) VALUES ('53196','Big Room/Washer-Dryer/Wifi/AC/JMZ');
INSERT INTO Listings_Info(listing_id,name) VALUES ('53469','cozy studio with parking spot');
INSERT INTO Listings_Info(listing_id,name) VALUES ('53470','Clean and convenient 2BR apartment');
INSERT INTO Listings_Info(listing_id,name) VALUES ('53477','3 floors of luxury!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('54158','The Institute—Heart of Williamsburg');
INSERT INTO Listings_Info(listing_id,name) VALUES ('54453','MIDTOWN WEST - Large alcove studio');
INSERT INTO Listings_Info(listing_id,name) VALUES ('54466','Beautiful Uptown Manhattan apartmnt');
INSERT INTO Listings_Info(listing_id,name) VALUES ('54508','Sml Rm in pr Brst  Park Sl great for Med/students');
INSERT INTO Listings_Info(listing_id,name) VALUES ('54544','City Room - Private Penthouse Apt.');
INSERT INTO Listings_Info(listing_id,name) VALUES ('54626','Cozy bedroom by Yankee Stadium');
INSERT INTO Listings_Info(listing_id,name) VALUES ('54860','Great apartment with private bathroom and entrance');
INSERT INTO Listings_Info(listing_id,name) VALUES ('55467','Private Garden Apt • New Renovation');
INSERT INTO Listings_Info(listing_id,name) VALUES ('55498','Modern comfort in art infused landmark Brownstone');
INSERT INTO Listings_Info(listing_id,name) VALUES ('55668','NOHO/EAST VILLAGE, PRIVATE 1/2 BATH');
INSERT INTO Listings_Info(listing_id,name) VALUES ('55737','Sleek & Comfortable Soho Apt');
INSERT INTO Listings_Info(listing_id,name) VALUES ('55959','Spacious Williamsburg Share w/ LOFT BED');
INSERT INTO Listings_Info(listing_id,name) VALUES ('55982','Cozy 2 br in sunny Fort Greene apt');
INSERT INTO Listings_Info(listing_id,name) VALUES ('56467','Cozy East Village Railroad 1 Bed!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('56525','1 Bedroom Loft w/ Private Roof Deck');
INSERT INTO Listings_Info(listing_id,name) VALUES ('56859','City Room - Private & Comfy Bedroom');
INSERT INTO Listings_Info(listing_id,name) VALUES ('57166','Elegant NYC Pad');
INSERT INTO Listings_Info(listing_id,name) VALUES ('57297','Clean & bright 1BR in Cobble Hill, GREAT location!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('57468','Modern, Large East Village Loft');
INSERT INTO Listings_Info(listing_id,name) VALUES ('57618','Great new apt, close to everything');
INSERT INTO Listings_Info(listing_id,name) VALUES ('57740','Quiet & Clean Retreat in the City');
INSERT INTO Listings_Info(listing_id,name) VALUES ('57754','Stylish Large Gramercy Loft!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('57874','The Brownstone-Luxury 1 Bd Apt/NYC');
INSERT INTO Listings_Info(listing_id,name) VALUES ('58059','PRIVATE Room on Historic Sugar Hill');
INSERT INTO Listings_Info(listing_id,name) VALUES ('58062','South Slope Green');
INSERT INTO Listings_Info(listing_id,name) VALUES ('58467','17 Flr. Manhattan Views, Nr. Subway');
INSERT INTO Listings_Info(listing_id,name) VALUES ('59014','Spacious 1BR, Adorable Clean Quiet');
INSERT INTO Listings_Info(listing_id,name) VALUES ('59121','Nice, clean, safe, convenient 3BR');
INSERT INTO Listings_Info(listing_id,name) VALUES ('59642','Franklin St Flat in Trendy Greenpoint Brooklyn');
INSERT INTO Listings_Info(listing_id,name) VALUES ('59709','Artistic, Cozy, and Spacious w/ Patio! Sleeps 5');
INSERT INTO Listings_Info(listing_id,name) VALUES ('59855','One bedroom Apt. in NYC');
INSERT INTO Listings_Info(listing_id,name) VALUES ('60164','Beautiful, elegant 3 bed SOHO loft');
INSERT INTO Listings_Info(listing_id,name) VALUES ('60457','Spacious Greenwich Village Apt');
INSERT INTO Listings_Info(listing_id,name) VALUES ('60611','SpaHa Studio Monthly Rental');
INSERT INTO Listings_Info(listing_id,name) VALUES ('60666','City Room - Private Luxury Suite');
INSERT INTO Listings_Info(listing_id,name) VALUES ('60673','Private Room/bath Luxurious Harlem');
INSERT INTO Listings_Info(listing_id,name) VALUES ('60680','The gem of the East Village');
INSERT INTO Listings_Info(listing_id,name) VALUES ('60794','Bright and spacious, garden below!');
INSERT INTO Listings_Info(listing_id,name) VALUES ('60948','ACCOMMODATIONS GALORE #2');
INSERT INTO Listings_Info(listing_id,name) VALUES ('61167','Colorful Private One Bedroom Apt');
INSERT INTO Listings_Info(listing_id,name) VALUES ('61224','Huge Chelsea Loft');
INSERT INTO Listings_Info(listing_id,name) VALUES ('61406','Great room in great location');
INSERT INTO Listings_Info(listing_id,name) VALUES ('61492','Exclusive Room with Private Bath in  LES');
INSERT INTO Listings_Info(listing_id,name) VALUES ('61509','Quiet, clean midtown apt w. elevato');
INSERT INTO Listings_Info(listing_id,name) VALUES ('62095','BK Sweet Suite w/Kitchen&FullBath');
INSERT INTO Listings_Info(listing_id,name) VALUES ('62427','Great East Village Apartment Rental');
INSERT INTO Listings_Info(listing_id,name) VALUES ('62430','BROWNSTONE SUNDRENCHED BEAUTY');
INSERT INTO Listings_Info(listing_id,name) VALUES ('62452','A SpeciaL!! Private Room in NY');
INSERT INTO Listings_Info(listing_id,name) VALUES ('62461','B NYC Staten Alternative...');
INSERT INTO Listings_Info(listing_id,name) VALUES ('62787','C Private Room By The Ferry');
INSERT INTO Listings_Info(listing_id,name) VALUES ('62891','Smallest House In The Village');
INSERT INTO Listings_Info(listing_id,name) VALUES ('62903','Beautiful modern studio apartment in heart of NYC');
INSERT INTO Listings_Info(listing_id,name) VALUES ('62925','Beautiful Landmarked Duplex');
INSERT INTO Listings_Info(listing_id,name) VALUES ('63299','BROOKLYN > Guest Room w/ Queen Bed in Williamsburg');
INSERT INTO Listings_Info(listing_id,name) VALUES ('63320','D Private Che@p Room 2 Explore NYC');
INSERT INTO Listings_Info(listing_id,name) VALUES ('63360','Safe cute near subway& Manhattan NY NY retro style');
INSERT INTO Listings_Info(listing_id,name) VALUES ('63546','Large and Cozy Private Bedroom');
INSERT INTO Listings_Info(listing_id,name) VALUES ('63573','Small tidy bedroom in duplex');
INSERT INTO Listings_Info(listing_id,name) VALUES ('63588','LL3');
