INSERT INTO Location(location_id,city,neighborhood) VALUES (00704,'Brooklyn','Kensington');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00705,'Manhattan','Midtown');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00610,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00611,'Brooklyn','Clinton Hill');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00612,'Manhattan','East Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00601,'Manhattan','Murray Hill');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00631,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00602,'Manhattan','Hell''s Kitchen');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00603,'Manhattan','Upper West Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00604,'Manhattan','Chinatown');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00605,'Manhattan','Upper West Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00703,'Manhattan','Hell''s Kitchen');
INSERT INTO Location(location_id,city,neighborhood) VALUES (07093,'Brooklyn','South Slope');
INSERT INTO Location(location_id,city,neighborhood) VALUES (07675,'Manhattan','Upper West Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (07677,'Manhattan','West Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (07885,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (07981,'Brooklyn','Fort Greene');
INSERT INTO Location(location_id,city,neighborhood) VALUES (07999,'Manhattan','Chelsea');
INSERT INTO Location(location_id,city,neighborhood) VALUES (08888,'Brooklyn','Crown Heights');
INSERT INTO Location(location_id,city,neighborhood) VALUES (08889,'Manhattan','East Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (07095,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (07481,'Brooklyn','Park Slope');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10451,'Brooklyn','Park Slope');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10452,'Brooklyn','Park Slope');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10453,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10454,'Brooklyn','Windsor Terrace');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10455,'Manhattan','Inwood');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10456,'Manhattan','Hell''s Kitchen');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10457,'Manhattan','Inwood');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10458,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10459,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10460,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10461,'Brooklyn','Greenpoint');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10462,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10463,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10464,'Brooklyn','South Slope');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10465,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10466,'Brooklyn','Bushwick');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10467,'Brooklyn','Flatbush');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10468,'Manhattan','Lower East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10469,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10470,'Brooklyn','South Slope');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10471,'Brooklyn','Fort Greene');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10472,'Manhattan','Upper West Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10473,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10474,'Brooklyn','Prospect-Lefferts Gardens');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10475,'Queens','Long Island City');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10499,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10001,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10002,'Brooklyn','Fort Greene');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10003,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10004,'Manhattan','Upper West Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10005,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10006,'Brooklyn','Greenpoint');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10007,'Manhattan','Kips Bay');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10008,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10009,'Manhattan','Lower East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10010,'Manhattan','Hell''s Kitchen');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10011,'Brooklyn','Greenpoint');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10012,'Manhattan','SoHo');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10013,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10014,'Manhattan','Chelsea');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10016,'Manhattan','Upper East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10017,'Brooklyn','Prospect Heights');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10018,'Brooklyn','Clinton Hill');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10019,'Manhattan','Hell''s Kitchen');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10020,'Brooklyn','Park Slope');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10021,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10022,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10023,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10024,'Manhattan','East Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10025,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10026,'Manhattan','Hell''s Kitchen');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10027,'Manhattan','Washington Heights');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10028,'Brooklyn','Clinton Hill');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10029,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10030,'Manhattan','Upper East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10031,'Queens','Woodside');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10032,'Brooklyn','Fort Greene');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10033,'Manhattan','Chelsea');
INSERT INTO Location(location_id,city,neighborhood) VALUES (10034,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00613,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00614,'Manhattan','Lower East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00714,'Brooklyn','Flatbush');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00616,'Manhattan','Lower East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00617,'Brooklyn','Brooklyn Heights');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00794,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00622,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00623,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00725,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00726,'Brooklyn','Bushwick');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00727,'Brooklyn','Prospect Heights');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00627,'Brooklyn','Clinton Hill');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00729,'Brooklyn','Prospect Heights');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00979,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00981,'Brooklyn','Bushwick');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00982,'Manhattan','Upper West Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00983,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00984,'Manhattan','Chelsea');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00985,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00986,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00987,'Brooklyn','Carroll Gardens');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00988,'Manhattan','Washington Heights');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00736,'Manhattan','West Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00737,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00735,'Brooklyn','Park Slope');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00742,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00638,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00739,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00769,'Brooklyn','Gowanus');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00782,'Manhattan','Hell''s Kitchen');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00783,'Brooklyn','Clinton Hill');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00780,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00775,'Brooklyn','South Slope');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00646,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00647,'Manhattan','Kips Bay');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00738,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00650,'Manhattan','Upper West Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00652,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00653,'Brooklyn','South Slope');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00784,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00785,'Brooklyn','South Slope');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00656,'Manhattan','Upper West Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00965,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00966,'Brooklyn','Prospect-Lefferts Gardens');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00968,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00969,'Manhattan','Upper East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00970,'Manhattan','Washington Heights');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00971,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00778,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00659,'Brooklyn','Clinton Hill');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00660,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00791,'Brooklyn','Greenpoint');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00792,'Manhattan','Lower East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00662,'Manhattan','Hell''s Kitchen');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00664,'Manhattan','West Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00795,'Brooklyn','Flatlands');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00777,'Brooklyn','Clinton Hill');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00667,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00786,'Brooklyn','Clinton Hill');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00669,'Brooklyn','Greenpoint');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00670,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00771,'Brooklyn','Cobble Hill');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00772,'Queens','Flushing');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00773,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00674,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00606,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00707,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00636,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00680,'Brooklyn','Fort Greene');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00681,'Manhattan','West Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00682,'Brooklyn','Prospect Heights');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00715,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00676,'Brooklyn','Prospect Heights');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00687,'Manhattan','East Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00718,'Manhattan','West Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00719,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00720,'Manhattan','Upper East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00723,'Brooklyn','Boerum Hill');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00624,'Manhattan','Upper East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00716,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00717,'Queens','Sunnyside');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00728,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00730,'Brooklyn','DUMBO');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00731,'Manhattan','Upper East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00732,'Brooklyn','Gowanus');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00733,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00734,'Brooklyn','Clinton Hill');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00740,'Brooklyn','Carroll Gardens');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00741,'Staten Island','St. George');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00678,'Brooklyn','Bushwick');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00677,'Bronx','Highbridge');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00744,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00721,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00745,'Manhattan','Financial District');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00637,'Brooklyn','Fort Greene');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00688,'Manhattan','West Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00952,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00751,'Manhattan','West Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00690,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00683,'Brooklyn','Fort Greene');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00901,'Queens','Ridgewood');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00902,'Manhattan','Morningside Heights');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00906,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00907,'Brooklyn','Park Slope');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00908,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00909,'Brooklyn','Prospect Heights');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00910,'Manhattan','Upper East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00911,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00912,'Manhattan','Chelsea');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00913,'Manhattan','Hell''s Kitchen');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00914,'Manhattan','Lower East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00915,'Brooklyn','South Slope');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00916,'Manhattan','Upper East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00917,'Manhattan','Lower East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00918,'Manhattan','Chelsea');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00919,'Queens','Jamaica');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00920,'Manhattan','Hell''s Kitchen');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00921,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00922,'Queens','Middle Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00923,'Queens','Ridgewood');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00924,'Queens','Middle Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00925,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00926,'Manhattan','Hell''s Kitchen');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00927,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00928,'Brooklyn','Prospect Heights');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00929,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00930,'Bronx','Highbridge');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00931,'Manhattan','East Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00933,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00934,'Brooklyn','Bedford-Stuyvesant');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00935,'Manhattan','NoHo');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00936,'Manhattan','West Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00937,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00939,'Brooklyn','Fort Greene');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00940,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00955,'Brooklyn','Greenpoint');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00956,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00957,'Queens','Ditmars Steinway');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00958,'Brooklyn','Cobble Hill');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00959,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00960,'Manhattan','Hell''s Kitchen');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00961,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00962,'Manhattan','Flatiron District');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00963,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00975,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00976,'Brooklyn','Windsor Terrace');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00977,'Manhattan','Roosevelt Island');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00978,'Manhattan','Lower East Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00754,'Queens','Ridgewood');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00685,'Brooklyn','Greenpoint');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00757,'Manhattan','Chinatown');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00953,'Manhattan','Midtown');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00954,'Manhattan','SoHo');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00949,'Manhattan','Greenwich Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00950,'Manhattan','East Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00951,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00641,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00692,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00693,'Manhattan','Upper West Side');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00694,'Manhattan','East Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00765,'Manhattan','Little Italy');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00766,'Manhattan','Chelsea');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00767,'Manhattan','Harlem');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00698,'Manhattan','Chinatown');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00801,'Manhattan','Midtown');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00802,'Brooklyn','East Flatbush');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00803,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00804,'Brooklyn','Bushwick');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00805,'Staten Island','Tompkinsville');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00820,'Staten Island','Tompkinsville');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00821,'Staten Island','Tompkinsville');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00822,'Manhattan','East Village');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00823,'Manhattan','Chelsea');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00824,'Brooklyn','Greenpoint');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00830,'Brooklyn','Williamsburg');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00831,'Staten Island','Tompkinsville');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00840,'Queens','Astoria');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00841,'Brooklyn','Kensington');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00850,'Brooklyn','Park Slope');
INSERT INTO Location(location_id,city,neighborhood) VALUES (00851,'Bronx','Clason Point');
